[preview]

max_width  = 1920
max_height = 1080

[plugin]

prepend_fetchers = [
	{ id = "git", name = "*", run  = "git" },
	{ id = "git", name = "*/", run  = "git" },
]

prepend_previewers = [
	{ url = "*.cu",  run = 'piper -- pygmentize -l cuda -O style=dracula "$1"' },
	{ url = "*.cuh", run = 'piper -- pygmentize -l cuda -O style=dracula "$1"' },
]
