export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# history setting
HISTFILE=~/.zhistory
HISTSIZE=50000
SAVEHIST=10000

# alias setting
if [ -f ~/.zsh_aliases ]; then
  source ~/.zsh_aliases
fi

# path setting
export PATH=$HOME/.local/bin:$PATH
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$HOME/.local/lib:$LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$HOME/.local/include:$CPLUS_INCLUDE_PATH
export C_INCLUDE_PATH=$HOME/.local/include:$C_INCLUDE_PATH

# make zsh compatible with *
setopt no_nomatch

# set keybind as emacs
bindkey -e

# plugins
source ~/.zsh/themes/powerlevel10k/powerlevel10k.zsh-theme
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
source ~/.zsh/plugins/z/z.sh

# completions setting
setopt AUTO_LIST
setopt AUTO_MENU
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' rehash true                              # automatically find new executables in path
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
# enable completion 
autoload -U compinit
compinit
